### ISSUE TITLE
Enabling IPv6 leads to network Flooding

### ISSUE THREAD

**Issue by mrosenbaum** [OpenELEC/OpenELEC.tv#3746]
I'm using OpenELEC 5.0 on an Intel Celeron NUC and on an older Zotac ZBox. As soon as I enable IPv6 (mode auto) my Network gets unusable as OpenELEC is flooding the net with DHCPv6 Requests like this one:
3794078	613.279746000	fe80::c23f:d5ff:fe65:fd5b	ff02::1:2	DHCPv6	120	Solicit XID: 0x2017bf CID: 000100011c3af7a6c03fd565fd5b 
This is reproducible, disabling IPv6 directly stops this behaviour.
Gateway is a FritzBox7390 with a Sixxs IPv6-Tunnel.

**Comment by mrosenbaum** [comment]
Hi,

I did a bit of debugging, changing the DHCPv6 behavior of the Fritzbox changed the flooding Message only slightly from Solicit to Information-request:
2014	117.518007000	fe80::ae7b:a1ff:fee7:5149	ff02::1:2	DHCPv6	100	Information-request XID: 0xac1a97 CID: 000100011c3c5516ac7ba1e75149 
connman is asking fro DNS-Server, Domainlist and Simple NTP server.
The debug-log on the openelec-machine gave a ton of log messages of this type:
Jan 04 19:46:31 Video-NUC connmand[2703]: /home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/connman-1.27/src/dhcpv6.c:timeout_info_req() info RT timeout 0 msec
A 0 millisecond-timeout looks a bit weird, but without real knowledge in C  I can't investigate that significantly deeper myself.

Disabling IPv6 in general seems to be a suitable short term fix, as this is a rather ugly bug - but in the long term this is not a solution as IPv6 is coming up more an more with a lot of DSlite connections and something like that.

Thanks

**Comment by chewitt** [comment]
If you "touch /storage/.config/debug.connman" then reboot or restart connman.service you put connman into debug mode; it will generate more connman specific output in the system log. If you can capture the log and paste it somewhere (use the internal paste function) we can take this to folks in the #connman IRC channel for investigation.

**Comment by mrosenbaum** [comment]
Thanks for the comment, I did some further testing, here are the logs:

Debug-Log: https://dl.dropboxusercontent.com/u/56554097/openelec.log
Wireshark-Log: https://dl.dropboxusercontent.com/u/56554097/openelec-ipv6.pcapng

The behaivior is the same on x86 and on x86_64

**Comment by stefansaraev** [comment]
01bf6480e8a0a13089f41ed28a9055295066baa0should be fixed in

**Comment by mrosenbaum** [comment]
Yes, this fixes it for me (tested with git openelec-5.0 8819fa2d5446e73f8707418931074900625447c4)

**Comment by pfl** [comment]
This should be fixed by commit 3ac3eb0d092439247375886fd2a193538e2449df that can be cherry-picked on top of 1.27.

**Comment by stefansaraev** [comment]
thanks. we will stick to 1.23 for stables.

and I'd guess it doesnt fix https://github.com/OpenELEC/OpenELEC.tv/issues/3536#issuecomment-69368924 ...
