### ISSUE TITLE
cec (anynet) cubox samsung tv not working at on/ off  

### ISSUE THREAD

**Issue by tunf** [OpenELEC/OpenELEC.tv#3941]
After start of tv or cubox cec / anynet (remote) is not working until selection on tv for kodi device. This is every on/off action on tv/ cubox. This is not happening at rpi2

This is also in openelec 5.0.4

**Comment by tunf** [comment]
kodi debug log cubox:

http://sprunge.us/hYRB

**Comment by tunf** [comment]
Same issue in openelec 5.0.5

**Comment by fritsch** [comment]
@wolfgar do you have any idea here?

**Comment by wolfgar** [comment]
Hi sorry too late now but I will had a detailed look at i tomorrow and report back

**Comment by tunf** [comment]
Today i also discovered that using my cubox on hdmi i'm not able to change the image and sound settings on my tv. Using other devices on this or other ports i can change video and audio settings.. Don't know if it is related but as info.

**Comment by amak79** [comment]
I have experienced this issue with my Cubox-i4Pro and Samsung LA46A650 since OE 5.0.0.

Debug log: http://paste.debian.net/plainh/14ce2968

**Comment by fritsch** [comment]
You say: since OE 5.0.0 - which version as the last version for you?

2015-03-11 12:05 GMT+01:00 amak79 <notifications@github.com>:

> I have experienced this issue with my Cubox-i4Pro and Samsung LA46A650
> since OE 5.0.0.
>
> Debug log: http://paste.debian.net/plainh/14ce2968
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3941#issuecomment-78243561>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by amak79** [comment]
I didn't state the OE version since it's in the debug log. I'm currently on OE 5.0.5.

**Comment by fritsch** [comment]
I asked: Which version was working? as you used the word "since".

2015-03-11 12:51 GMT+01:00 amak79 <notifications@github.com>:

> I didn't state the OE version since it's in the debug log. I'm currently
> on OE 5.0.5.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3941#issuecomment-78249052>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by amak79** [comment]
I'm sorry I misunderstood your question. It has never worked correctly. OE 5.0.0 was the first version I installed on the Cubox-i4Pro.

**Comment by fritsch** [comment]
Good - that's what I was curious about. Though I had hoped for a
regressions, but was quite sure there were no changes in that regard.
Upstream dev is already involved - I am looking forward to 6.0 :-)

2015-03-11 13:37 GMT+01:00 amak79 <notifications@github.com>:

> I'm sorry I misunderstood your question. It has never worked correctly. OE
> 5.0.0 was the first version I installed on the Cubox-i4Pro.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3941#issuecomment-78254723>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by tunf** [comment]
The issues looks to be still there using 5.0.6, will test some more as i got some more issues after the update (Screen not fitting, not booting until usb dvd is disconnected) so to be sure i will start fresh and start with older and update this one...

**Comment by stefansaraev** [comment]
it will for sure be fixed in 5.2. fingers crossed!

**Comment by tunf** [comment]
That sounds like a great deal! Testing is a dev, no still not working. Will keep my fingers and toe crossed, just to be sure. Thanks for the good work this far.

**Comment by mk01** [comment]
@amak79 

the log would be needed with EXTRA cec logging (a change in Kodi). without the cec communication details there is very few to follow.

**Comment by amak79** [comment]
@mk01 

I have updated my original post with a new debug log, which has cec component logging enabled.

**Comment by mk01** [comment]
@amak79 

that particular problem comes from combination of both XBMC's way of initialising CECPeripheralDevice (it spoils libCec's write queue by scanning whole Cec bus - in parallel with request to become ActiveSource) and the way how driver(kernel) handles msg writes from userspace (it blocks libCec's write threads until actual ACK/NOACK/Timeout).

as result, TV is not getting replies in time and considers device(XBMC) not present.

**Comment by mrobinson86** [comment]
Are there any combinations of settings that are expected to work around this?

**Comment by samweisgamdschie** [comment]
Hi there!

same here with cubox-i4pro and anynet. I just wanted to say it works when I go to settings -> system -> input devices -> devices -> CEC Adapter and set to standard. I guess it will restart the driver. Maybe it's possible to get rid of this problem by delaying it at boot time (even if it's a nasty workaround).

**Comment by chewitt** [comment]
is this still and issue on OE 6.0.0 - or can we close out the ticket?

**Comment by tunf** [comment]
Still an issue and would be great if this will be fixed for live!

**Comment by phunkyfish** [comment]
Yes, still an issue on 6.0.0. I got my cubox 3 weeks ago but have stopped using it. It disconnects CEC so often Its not usuable. Appears to be random. A shame as its a great device other than that.

**Comment by phunkyfish** [comment]
I just installed 6.0.1 and unfortunately this is still a problem. Any further info on when it may be fixed?

**Comment by sraue** [comment]
please report to https://github.com/Pulse-Eight/libcec (CEC support for imx6 has to be implemented there)
